version: "3"

services:

  mongodb:
    container_name: mymongodb
    image: mongo
    ports:
      - "27017:27017"
    restart: always

  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: string
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always

  app-http:
    container_name: app-http
    image: vladfedorenko1/spring:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysqldb
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mymongodb:27017
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/string
      SPRING_DATASOURCE_USERNAME: root

  webserver:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/nginx.conf/:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw